language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm i -g vuepress
  - npm i @fortawesome/fontawesome-svg-core
  - npm i @fortawesome/free-solid-svg-icons
  - npm i @fortawesome/vue-fontawesome
  - npm i @fortawesome/free-brands-svg-icons
  - npm i @fortawesome/free-regular-svg-icons
  - npm i -D vuetify
  - npm i -D vuepress-plugin-smooth-scroll
script:
  - npm run docs:build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  repo: gregless22/gregless22.github.io
  keep-history: true
  target-branch: master
  on:
    branch: master
