version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: build it
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/project
          paths: 
          - dist
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3    
    steps:
      - attach_workspace:
          at: ./dist
      - add_ssh_key:
          fingerprints:
            - "ff:50:95:17:39:44:3c:5d:82:81:7f:87:03:ec:2e:48"
      - run:
          name: Deploy Over SSH to github
          command: ssh git@github.com:gregless22/gregless22.github.io.git "git push origin master"
 

workflows:
    build_and_deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
