version: 2.1
jobs:
  build:
    executor: node-executor 
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: build it
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/project
          paths: 
          - dist
  deploy:
    executor: node-executor    
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - "ff:50:95:17:39:44:3c:5d:82:81:7f:87:03:ec:2e:48"
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH to github
          command: |
            mkdir temp
            cd temp
            git init
            git clone git@github.com:gregless22/gregless22.github.io.git
            git config user.email "sayhi@circleci.com"
            git config user.name "Deployment Bot"
            cd ..
            cp -Rf dist/. temp/
            cd temp
            pwd
            git add -A
            git commit -m 'CircleCI Deploy'
            git push git@github.com:gregless22/gregless22.github.io.git master

workflows:
    build_and_deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build

executors:
    node-executor:
      working_directory: ~/project
      docker:
        - image: circleci/node:latest