version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - persist_to_workspace:
              root: .
              paths: 
                - /dist
  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
        at: ./dist
      - run:
        name: Deploy Over SSH
        command:
        #  ssh $SSH_USER@$SSH_HOST "<remote deploy command>""
  # deploy to git hub

workflows:
    build_and_deploy:
      jobs:
        - build
        # - deploy:
        #   requires:
        #     - build
        #   filters:
        #      branches:
        #         only: master