version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      working-directory: .
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - persist-to-workspace:
              root: .
              paths: 
                - /dist
  deploy:
    executor:
      name: node/default
      working-directory: .
    steps:
      - attach-workspace:
        at: ./dist
      # - deploy:


  # deploy to git hub

workflows:
    build_and_deploy:
      jobs:
        - build
        - deploy:
          requires:
            - build